AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  CacheRootDirectory: tmp/rubocop_cache

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 140

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ParameterLists:
  Max: 6

Naming/MethodParameterName:
  AllowedNames:
    - "n"

Gemspec/DevelopmentDependencies:
  Enabled: false
